# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html
# and https://foundry-rs.github.io/starknet-foundry/projects/configuration.html for more information

[sncast.testnet]
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_8"
accounts-file = "accounts.json"
account = "starkremit_account"
wait-params = { timeout = 300, retry-interval = 10 }
block-explorer = "StarkScan"
show-explorer-links = true

[sncast.mainnet]
url = "https://starknet-mainnet.public.blastapi.io/rpc/v0_8"
accounts-file = "accounts.json"
account = "starkremit_account"
wait-params = { timeout = 300, retry-interval = 10 }
block-explorer = "StarkScan"
show-explorer-links = true
